#每天更新refresh_token
name: 更新refresh_token

on: 
  workflow_dispatch:
  schedule:
    - cron: '13 16 * * *'
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install requests and nacl #安装requests和nacl模块
      run: |
        pip install requests
        pip install PyNaCl
    - name: update secrets #更新token到secret
      env: 
        #github的账号信息
        GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        GH_REPO: ${{ github.repository }}
        #以下是微软的账号信息（修改以下，类推复制增加）
        APP_NUM: ${{ secrets.APP_NUM }} 
        #账号/应用1
        MS_TOKEN: ${{ secrets.MS_TOKEN }} 
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        #账号/应用2
        #MS_TOKEN_2: ${{ secrets.MS_TOKEN_2 }} 
        #CLIENT_ID_2: ${{ secrets.CLIENT_ID_2 }}
        #CLIENT_SECRET_2: ${{ secrets.CLIENT_SECRET_2 }}
      run: |
        python updatetoken.py
